export const exampleJSON = [{
  title: 'Pick up meals to take home.',
  location: 'San Francisco Unified School District',
  description: 'Access 18 sites that will be open 11:00am - 12:00pm Mondays and Wednesdays, to pick up breakfast, lunch, supper, fresh fruit, vegetables and milk to take home. 2 days’ worth of food is distributed on Monday, and 3 days’ worth on Wednesday. Some of the locations listed have open pantry hours.',
  address: 'Multiple locations go to website for more info',
  call: '123-456-7890',
  website: 'http://localhost:8081/',
  directions: 'http://localhost:8081/',
}, {
  title: 'Receive three day supply of shelf stable food.',
  location: 'Emergency Food Box Program',
  description: 'Three day supply of shelf stable foods for individuals with urgent need ',
  address: 'call 211 for list of locations',
  call: '211',
  website: 'http://localhost:8081/',
  directions: 'http://localhost:8081/',
}, {
  title: 'Get breakfast and dinners.',
  location: 'Mother Brown’s Kitchen ',
  description: 'Mother Brown’s Kitchen is open Monday - Friday, and is serving breakfast at 7:30am and dinner at 4:30pm. All meals are packaged to-go. Located at 2111 Jennings Street.',
  address: '2111 Jennings St.',
  call: '211',
  website: 'http://localhost:8081/',
  directions: 'http://localhost:8081/',
}, {
  title: 'Receive three day supply of shelf stable food.',
  location: 'Emergency Food Box Program',
  description: 'Three day supply of shelf stable foods for individuals with urgent need ',
  address: 'call 211 for list of locations',
  call: '211',
  website: 'http://localhost:8081/',
  directions: 'http://localhost:8081/',
}, {
  title: 'Receive three day supply of shelf stable food.',
  location: 'Emergency Food Box Program',
  description: 'Three day supply of shelf stable foods for individuals with urgent need ',
  address: 'call 211 for list of locations',
  call: '211',
  website: 'http://localhost:8081/',
  directions: 'http://localhost:8081/',
}, {
  title: 'Receive three day supply of shelf stable food.',
  location: 'Emergency Food Box Program',
  description: 'Three day supply of shelf stable foods for individuals with urgent need ',
  address: 'call 211 for list of locations',
  call: '211',
  website: 'http://localhost:8081/',
  directions: 'http://localhost:8081/',
}, {
  title: 'Receive three day supply of shelf stable food.',
  location: 'Emergency Food Box Program',
  description: 'Three day supply of shelf stable foods for individuals with urgent need ',
  address: 'call 211 for list of locations',
  call: '211',
  website: 'http://localhost:8081/',
  directions: 'http://localhost:8081/',
}];
